#!/usr/bin/env python3
import random
import subprocess
import sys


def random_case(x: str, p: float):
    return x.upper() if random.uniform(0, 1) <= p else x.lower()


def irony(s: str, p: float):
    return ''.join(map(lambda x: random_case(x, p), s))


def to_clipboard(x):
    os = sys.platform
    if os == 'linux':
        subprocess.run(f'echo -n "{x}" | xclip -sel clip', shell=True)
    elif os == 'darwin':
        subprocess.run(f'echo -n "{x}" | pbcopy', shell=True)
    elif os == 'win32':
        subprocess.run(f'echo -n "{x}" | clip', shell=True)


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('message', help='message to ironify')
    parser.add_argument('-x', '--copy', help='copy ironyc message to clipboard', action='store_true')
    parser.add_argument('-p', '--probability', help='probability of upper case letters', type=float, default=0.5)
    parser.add_argument('-q', '--quiet', help='does not print to terminal', action='store_true')
    args = parser.parse_args()

    output = irony(args.message, args.probability)

    if args.copy:
        to_clipboard(output)

    if not args.quiet:
        print(output)
